image: debian:bullseye

before_script:
  - apt-get update && apt-get install -y openssh-client

stages:
  - deploy

deploy-job:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo -e "$GITLAB_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 176.118.167.85 >> ~/.ssh/known_hosts
    - ssh root@176.118.167.85 "cd /home/beautyms/workspace/sites/beautyms.ru && ./deploy.sh"
  only:
    - main